server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/ms-pedido
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.rabbitmq.address=amqps://gvfkfwjf:vFzGY3GrCCBhLny_fquvDVrAeZuWhrhp@jaragua.lmq.cloudamqp.com/gvfkfwjf
broker.queue.processamento.name=exchange-processamento
